### PR TITLE
Added support for doc block methods and properties.

### PR DESCRIPTION
**Pull request by bravoman**
Please have a look and tell me what you think ;)

### CODE REVIEW

**Comment by davidfuhr** [comment]
Great feature! Could you please add some test cases?

**Comment by bravoman** [comment]
Will do, as soon as I come back from my holidays ;)

**Comment by bravoman** [comment]
I think the latest errors while building were because of a problem with github (because of a DDOS attack [right now](https://status.github.com/)).

**Comment by davidfuhr** [comment]
Merged.

**Pull request closed without merging**
